name: Generate GitHub Languages

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate languages statistics
        uses: cicirello/user-statistician@v1
        with:
          image-file: images/languages.svg
          hide-keys: general, contributions, repositories
          max-languages: 10
          commit-and-push: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
