name: Generate GitHub Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
      - name: Generate stats
        uses: cicirello/user-statistician@v1.25.0
        with:
          image-file: stats.svg
          commit-and-push: true
          locale: pt
        env:
          GH_TOKEN: ${{ github.token }}
