name: user-statistician

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate the languages distribution
        uses: cicirello/user-statistician@v1
        with:
          image-file: images/languages.svg
          hide-keys: general, contributions, repositories
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
